DROP DATABASE IF EXISTS webDesignDB;
CREATE DATABASE IF NOT EXISTS webDesignDB;
USE webDesignDB;

CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);